---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: kafka
    run_list:
      - "java::default"
      - recipe[kafka-config::default]
    attributes:
